a = [
    {
        "object": "page",
        "id": "15c745b7-8a2c-8169-a9bd-ed84b2f4f202",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Senior Welcome", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Senior Welcome",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Senior-Welcome-15c745b78a2c8169a9bded84b2f4f202",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81a4-9f41-e1329ad889c4",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Newborn Welcome", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Newborn Welcome",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Newborn-Welcome-15c745b78a2c81a49f41e1329ad889c4",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81c9-877f-dd6b81d8cd76",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Newborn Portraits", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Newborn Portraits",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Newborn-Portraits-15c745b78a2c81c9877fdd6b81d8cd76",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81d3-8231-d35634981e0b",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:58:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Family Portraits", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Family Portraits",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Family-Portraits-15c745b78a2c81d38231d35634981e0b",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81af-a043-e391f394952d",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Family Welcome", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Family Welcome",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Family-Welcome-15c745b78a2c81afa043e391f394952d",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81e7-9e41-d0df64b7c8eb",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Senior Portraits ", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Senior Portraits ",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Senior-Portraits-15c745b78a2c81e79e41d0df64b7c8eb",
        "public_url": None,
    },
][
    {
        "object": "page",
        "id": "15c745b7-8a2c-8169-a9bd-ed84b2f4f202",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Senior Welcome", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Senior Welcome",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Senior-Welcome-15c745b78a2c8169a9bded84b2f4f202",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81a4-9f41-e1329ad889c4",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Newborn Welcome", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Newborn Welcome",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Newborn-Welcome-15c745b78a2c81a49f41e1329ad889c4",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81c9-877f-dd6b81d8cd76",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Newborn Portraits", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Newborn Portraits",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Newborn-Portraits-15c745b78a2c81c9877fdd6b81d8cd76",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81d3-8231-d35634981e0b",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:58:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Family Portraits", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Family Portraits",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Family-Portraits-15c745b78a2c81d38231d35634981e0b",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81af-a043-e391f394952d",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Family Welcome", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Family Welcome",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Family-Welcome-15c745b78a2c81afa043e391f394952d",
        "public_url": None,
    },
    {
        "object": "page",
        "id": "15c745b7-8a2c-81e7-9e41-d0df64b7c8eb",
        "created_time": "2024-12-14T02:56:00.000Z",
        "last_edited_time": "2024-12-14T02:59:00.000Z",
        "created_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "last_edited_by": {"object": "user", "id": "60c25ffc-f0c9-4cfe-a81b-4e55245d528a"},
        "cover": None,
        "icon": None,
        "parent": {"type": "database_id", "database_id": "15c745b7-8a2c-81df-84d5-e04084785758"},
        "archived": False,
        "in_trash": False,
        "properties": {
            "Tags": {"id": "I%60td", "type": "multi_select", "multi_select": []},
            "Name": {
                "id": "title",
                "type": "title",
                "title": [
                    {
                        "type": "text",
                        "text": {"content": "Senior Portraits ", "link": None},
                        "annotations": {
                            "bold": False,
                            "italic": False,
                            "strikethrough": False,
                            "underline": False,
                            "code": False,
                            "color": "default",
                        },
                        "plain_text": "Senior Portraits ",
                        "href": None,
                    }
                ],
            },
        },
        "url": "https://www.notion.so/Senior-Portraits-15c745b78a2c81e79e41d0df64b7c8eb",
        "public_url": None,
    },
]
